export const dashboardData = {
  metrics: [
    {
      id: 'active-loads',
      label: 'Active Loads',
      value: '247',
      note: '+12% from yesterday',
      icon: 'truck',
      iconTone: 'bg-blue-100 text-blue-600',
      noteTone: 'text-emerald-600',
    },
    {
      id: 'on-time',
      label: 'On-time %',
      value: '94.2%',
      note: '+2.1% this week',
      icon: 'clock',
      iconTone: 'bg-emerald-100 text-emerald-600',
      noteTone: 'text-emerald-600',
    },
    {
      id: 'trucks-available',
      label: 'Trucks Available',
      value: '89',
      note: 'of 156 total',
      icon: 'fleet',
      iconTone: 'bg-violet-100 text-violet-600',
      noteTone: 'text-slate-500',
    },
    {
      id: 'exceptions',
      label: 'Exceptions',
      value: '12',
      note: '3 critical alerts',
      icon: 'alert',
      iconTone: 'bg-rose-100 text-rose-600',
      noteTone: 'text-rose-500',
    },
    {
      id: 'fuel-cost',
      label: 'Fuel Cost (MTD)',
      value: '$89.2K',
      note: '+8% vs target',
      icon: 'fuel',
      iconTone: 'bg-amber-100 text-amber-600',
      noteTone: 'text-rose-500',
    },
    {
      id: 'revenue',
      label: 'Revenue (MTD)',
      value: '$1.2M',
      note: '+15% vs last month',
      icon: 'revenue',
      iconTone: 'bg-emerald-100 text-emerald-600',
      noteTone: 'text-emerald-600',
    },
  ],
  vehicles: [
    { id: 'FL-4892', lat: 32.7795, lng: -96.7972, status: 'on-time' },
    { id: 'TX-7841', lat: 35.4678, lng: -97.5138, status: 'on-time' },
    { id: 'NY-1847', lat: 32.95, lng: -94.73, status: 'delayed' },
    { id: 'IL-5629', lat: 31.81, lng: -99.31, status: 'critical' },
    { id: 'CA-3952', lat: 30.92, lng: -95.85, status: 'critical' },
    { id: 'GA-9273', lat: 34.1, lng: -84.43, status: 'on-time' },
  ],
  mapSummary: [
    { id: 'total-vehicles', label: 'Total Vehicles', value: '156', valueTone: 'text-slate-800' },
    { id: 'available', label: 'Available', value: '89', valueTone: 'text-emerald-600' },
    { id: 'active-loads', label: 'Active Loads', value: '247', valueTone: 'text-blue-600' },
  ],
  dispatches: [
    {
      id: 'LD-2024-001847',
      route: 'Chicago - Atlanta',
      driver: 'Mike Rodriguez',
      status: 'In Transit',
    },
    {
      id: 'LD-2024-001848',
      route: 'Dallas - Phoenix',
      driver: 'Jennifer Chen',
      status: 'Assigned',
    },
    {
      id: 'LD-2024-001849',
      route: 'Los Angeles - Seattle',
      driver: 'David Thompson',
      status: 'Loading',
    },
    {
      id: 'LD-2024-001850',
      route: 'Miami - Jacksonville',
      driver: 'Maria Santos',
      status: 'Delivered',
    },
    {
      id: 'LD-2024-001851',
      route: 'Houston - New Orleans',
      driver: 'Robert Wilson',
      status: 'Unassigned',
    },
    {
      id: 'LD-2024-001852',
      route: 'Denver - Kansas City',
      driver: 'Lisa Anderson',
      status: 'In Transit',
    },
    {
      id: 'LD-2024-001853',
      route: 'Portland - San Francisco',
      driver: 'James Martinez',
      status: 'Assigned',
    },
    {
      id: 'LD-2024-001854',
      route: 'Nashville - Memphis',
      driver: 'Amanda Taylor',
      status: 'Loading',
    },
  ],
  orders: [
    {
      id: 'LD-2024-001847',
      customerName: 'Walmart Distribution',
      customerType: 'Enterprise Customer',
      customerCode: 'WM',
      customerTone: 'bg-blue-600',
      origin: 'Chicago, IL',
      destination: 'Atlanta, GA',
      eta: 'Feb 8, 14:30',
      status: 'In Transit',
      priority: 'High',
      driver: 'Mike Rodriguez',
      truck: 'FL-4892',
      rate: '$2,850',
      margin: '18.5%',
      pod: true,
    },
    {
      id: 'LD-2024-001848',
      customerName: 'Target Corporation',
      customerType: 'Premium Customer',
      customerCode: 'TG',
      customerTone: 'bg-rose-600',
      origin: 'Dallas, TX',
      destination: 'Phoenix, AZ',
      eta: 'Feb 9, 09:15',
      status: 'Assigned',
      priority: 'Medium',
      driver: 'Jennifer Chen',
      truck: 'TX-7841',
      rate: '$1,950',
      margin: '22.1%',
      pod: false,
    },
    {
      id: 'LD-2024-001849',
      customerName: 'Amazon Logistics',
      customerType: 'High Volume',
      customerCode: 'AM',
      customerTone: 'bg-orange-500',
      origin: 'Los Angeles, CA',
      destination: 'Seattle, WA',
      eta: 'Feb 8, 22:45',
      status: 'Loading',
      priority: 'High',
      driver: 'David Thompson',
      truck: 'CA-3952',
      rate: '$3,200',
      margin: '15.8%',
      pod: false,
    },
    {
      id: 'LD-2024-001850',
      customerName: 'FedEx Ground',
      customerType: 'Express Service',
      customerCode: 'FX',
      customerTone: 'bg-violet-600',
      origin: 'Miami, FL',
      destination: 'Jacksonville, FL',
      eta: 'Feb 7, 16:20',
      status: 'Delivered',
      priority: 'Low',
      driver: 'Maria Santos',
      truck: 'FL-2847',
      rate: '$850',
      margin: '28.2%',
      pod: true,
    },
    {
      id: 'LD-2024-001851',
      customerName: 'Home Depot Supply',
      customerType: 'Regular Customer',
      customerCode: 'HD',
      customerTone: 'bg-teal-600',
      origin: 'Houston, TX',
      destination: 'New Orleans, LA',
      eta: 'Feb 9, 11:00',
      status: 'Unassigned',
      priority: 'Medium',
      driver: 'Not assigned',
      truck: '-',
      rate: '$1,450',
      margin: '19.3%',
      pod: false,
    },
    {
      id: 'LD-2024-001852',
      customerName: 'Costco Wholesale',
      customerType: 'Bulk Orders',
      customerCode: 'CS',
      customerTone: 'bg-indigo-600',
      origin: 'Denver, CO',
      destination: 'Kansas City, MO',
      eta: 'Feb 8, 19:30',
      status: 'In Transit',
      priority: 'High',
      driver: 'Lisa Anderson',
      truck: 'CO-5629',
      rate: '$2,100',
      margin: '21.4%',
      pod: false,
    },
    {
      id: 'LD-2024-001853',
      customerName: 'Safeway Distribution',
      customerType: 'Food & Beverage',
      customerCode: 'SF',
      customerTone: 'bg-green-600',
      origin: 'Portland, OR',
      destination: 'San Francisco, CA',
      eta: 'Feb 9, 07:45',
      status: 'Assigned',
      priority: 'Medium',
      driver: 'James Martinez',
      truck: 'OR-9273',
      rate: '$1,750',
      margin: '17.1%',
      pod: false,
    },
    {
      id: 'LD-2024-001854',
      customerName: 'Kroger Supply Chain',
      customerType: 'Grocery Distribution',
      customerCode: 'KR',
      customerTone: 'bg-pink-600',
      origin: 'Nashville, TN',
      destination: 'Memphis, TN',
      eta: 'Feb 8, 15:20',
      status: 'Loading',
      priority: 'Low',
      driver: 'Amanda Taylor',
      truck: 'TN-4851',
      rate: '$980',
      margin: '25.5%',
      pod: false,
    },
    {
      id: 'LD-2024-001855',
      customerName: 'Best Buy Logistics',
      customerType: 'Retail Electronics',
      customerCode: 'BB',
      customerTone: 'bg-sky-600',
      origin: 'Minneapolis, MN',
      destination: 'Omaha, NE',
      eta: 'Feb 10, 08:40',
      status: 'Assigned',
      priority: 'Medium',
      driver: 'Eric Matthews',
      truck: 'MN-7712',
      rate: '$1,640',
      margin: '18.9%',
      pod: false,
    },
    {
      id: 'LD-2024-001856',
      customerName: 'CVS Distribution',
      customerType: 'Pharma Supplies',
      customerCode: 'CV',
      customerTone: 'bg-red-600',
      origin: 'Columbus, OH',
      destination: 'Detroit, MI',
      eta: 'Feb 10, 12:15',
      status: 'In Transit',
      priority: 'High',
      driver: 'Thomas Reed',
      truck: 'OH-3345',
      rate: '$1,980',
      margin: '20.4%',
      pod: false,
    },
    {
      id: 'LD-2024-001857',
      customerName: 'IKEA Fulfillment',
      customerType: 'Furniture Cargo',
      customerCode: 'IK',
      customerTone: 'bg-yellow-600',
      origin: 'Baltimore, MD',
      destination: 'Richmond, VA',
      eta: 'Feb 10, 17:05',
      status: 'Loading',
      priority: 'Low',
      driver: 'Daniel Clark',
      truck: 'MD-6621',
      rate: '$1,120',
      margin: '23.2%',
      pod: false,
    },
    {
      id: 'LD-2024-001858',
      customerName: 'PepsiCo Freight',
      customerType: 'Beverage Fleet',
      customerCode: 'PP',
      customerTone: 'bg-cyan-600',
      origin: 'St. Louis, MO',
      destination: 'Indianapolis, IN',
      eta: 'Feb 10, 19:45',
      status: 'In Transit',
      priority: 'High',
      driver: 'Rachel Moore',
      truck: 'MO-9204',
      rate: '$2,250',
      margin: '19.8%',
      pod: false,
    },
    {
      id: 'LD-2024-001859',
      customerName: "Lowe's Supply",
      customerType: 'Home Improvement',
      customerCode: 'LW',
      customerTone: 'bg-blue-700',
      origin: 'Charlotte, NC',
      destination: 'Birmingham, AL',
      eta: 'Feb 11, 06:20',
      status: 'Assigned',
      priority: 'Medium',
      driver: 'Nathan Hill',
      truck: 'NC-4019',
      rate: '$1,730',
      margin: '18.1%',
      pod: false,
    },
    {
      id: 'LD-2024-001860',
      customerName: '7-Eleven Network',
      customerType: 'Store Replenishment',
      customerCode: 'SE',
      customerTone: 'bg-emerald-700',
      origin: 'Las Vegas, NV',
      destination: 'Salt Lake City, UT',
      eta: 'Feb 11, 09:35',
      status: 'Unassigned',
      priority: 'Low',
      driver: 'Not assigned',
      truck: '-',
      rate: '$1,410',
      margin: '16.5%',
      pod: false,
    },
    {
      id: 'LD-2024-001861',
      customerName: 'Whole Foods Market',
      customerType: 'Fresh Goods',
      customerCode: 'WF',
      customerTone: 'bg-green-700',
      origin: 'Sacramento, CA',
      destination: 'Reno, NV',
      eta: 'Feb 11, 13:10',
      status: 'Delivered',
      priority: 'Medium',
      driver: 'Olivia Parker',
      truck: 'CA-7708',
      rate: '$980',
      margin: '27.6%',
      pod: true,
    },
    {
      id: 'LD-2024-001862',
      customerName: 'Sysco Logistics',
      customerType: 'Foodservice Bulk',
      customerCode: 'SY',
      customerTone: 'bg-slate-700',
      origin: 'Tulsa, OK',
      destination: 'Little Rock, AR',
      eta: 'Feb 11, 18:25',
      status: 'In Transit',
      priority: 'High',
      driver: 'Brian Scott',
      truck: 'OK-5526',
      rate: '$1,860',
      margin: '20.7%',
      pod: false,
    },
    {
      id: 'LD-2024-001863',
      customerName: 'Wayfair Network',
      customerType: 'Furniture Retail',
      customerCode: 'WY',
      customerTone: 'bg-violet-700',
      origin: 'Cleveland, OH',
      destination: 'Buffalo, NY',
      eta: 'Feb 12, 07:50',
      status: 'Loading',
      priority: 'Medium',
      driver: 'Sophia Perez',
      truck: 'OH-8870',
      rate: '$1,520',
      margin: '17.8%',
      pod: false,
    },
    {
      id: 'LD-2024-001864',
      customerName: 'Nike Distribution',
      customerType: 'Apparel Express',
      customerCode: 'NK',
      customerTone: 'bg-gray-800',
      origin: 'Portland, OR',
      destination: 'Boise, ID',
      eta: 'Feb 12, 10:15',
      status: 'Assigned',
      priority: 'High',
      driver: 'Kevin Adams',
      truck: 'OR-3921',
      rate: '$1,690',
      margin: '19.5%',
      pod: false,
    },
  ],
  alerts: [
    {
      id: 'late-pickup',
      title: 'Late Pickup Alert',
      detail: 'Load LD-2024-001845 is 2 hours behind schedule',
      meta: 'Customer: Walmart Distribution | ETA: 14:30',
      tone: 'rose',
    },
    {
      id: 'hos-warning',
      title: 'HOS Risk Warning',
      detail: 'Driver Mike Rodriguez approaching 11-hour limit',
      meta: 'Truck: FL-4892 | Time remaining: 1h 23m',
      tone: 'amber',
    },
    {
      id: 'temperature-alert',
      title: 'Temperature Alert',
      detail: 'Reefer unit temperature out of range (-18C to -20C)',
      meta: 'Load: LD-2024-001843 | Current: -15C',
      tone: 'blue',
    },
    {
      id: 'unpaid-invoice',
      title: 'Unpaid Invoice',
      detail: 'Invoice INV-2024-0892 overdue by 15 days',
      meta: 'Customer: Target Corp | Amount: $4,250.00',
      tone: 'yellow',
    },
  ],
  quickActions: [
    { id: 'create-load', label: 'Create Load', icon: 'create', style: 'bg-blue-500 hover:bg-blue-600' },
    { id: 'assign-driver', label: 'Assign Driver', icon: 'assign', style: 'bg-emerald-500 hover:bg-emerald-600' },
    { id: 'generate-invoice', label: 'Generate Invoice', icon: 'invoice', style: 'bg-violet-600 hover:bg-violet-700' },
    { id: 'plan-route', label: 'Plan Route', icon: 'route', style: 'bg-orange-500 hover:bg-orange-600' },
  ],
  fleetSummary: [
    { id: 'total', label: 'Total Vehicles', value: '127', textTone: 'text-blue-700', labelTone: 'text-blue-600/80', icon: 'Car', iconTone: 'bg-blue-500', bgScale: 'bg-blue-50 border-blue-100' },
    { id: 'available', label: 'Available', value: '89', textTone: 'text-emerald-700', labelTone: 'text-emerald-600/80', icon: 'CheckCircle2', iconTone: 'bg-emerald-500', bgScale: 'bg-emerald-50 border-emerald-100' },
    { id: 'in-use', label: 'In Use', value: '31', textTone: 'text-amber-600', labelTone: 'text-amber-600/80', icon: 'Truck', iconTone: 'bg-amber-400', bgScale: 'bg-[#fffcf0] border-amber-100' },
    { id: 'maintenance', label: 'Maintenance', value: '7', textTone: 'text-rose-700', labelTone: 'text-rose-600/80', icon: 'Wrench', iconTone: 'bg-rose-500', bgScale: 'bg-rose-50 border-rose-100' },
    { id: 'health', label: 'Health Score', value: '92%', textTone: 'text-purple-700', labelTone: 'text-purple-600/80', icon: 'HeartPulse', iconTone: 'bg-purple-500', bgScale: 'bg-purple-50 border-purple-100' },
  ],
  fleet: [
    {
      id: 'FL-4892', plate: 'FL-4892', model: 'Freightliner Cascadia', category: 'Semi-Truck',
      image: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=100&h=80&fit=crop&q=80',
      status: 'Available', statusTone: 'bg-emerald-100/60 text-emerald-600',
      driver: 'Michael Rodriguez', driverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop', driverStatus: 'Available',
      location: 'Chicago, IL', depot: 'Chicago Hub Terminal',
      lastPingLabel: '2 minutes ago', lastPingDate: 'Feb 9, 14:32',
      health: 'Good', healthDot: 'bg-emerald-400'
    },
    {
      id: 'TX-7841', plate: 'TX-7841', model: 'Peterbilt 579', category: 'Semi-Truck',
      image: 'https://images.unsplash.com/photo-1586191552066-d52cd3ae57bf?w=100&h=80&fit=crop&q=80',
      status: 'In Use', statusTone: 'bg-amber-100/60 text-amber-600',
      driver: 'Jennifer Chen', driverAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop', driverStatus: 'On Route',
      location: 'Dallas, TX', depot: 'En route to Phoenix',
      lastPingLabel: '5 minutes ago', lastPingDate: 'Feb 9, 14:29',
      health: 'Good', healthDot: 'bg-emerald-400'
    },
    {
      id: 'CA-3952', plate: 'CA-3952', model: 'Volvo VNL 860', category: 'Semi-Truck',
      image: 'https://images.unsplash.com/photo-1610416390145-c454e954a1be?w=100&h=80&fit=crop&q=80',
      status: 'Maintenance', statusTone: 'bg-rose-100/60 text-rose-600',
      driver: 'Unassigned', driverAvatar: '', driverStatus: 'In maintenance',
      location: 'Los Angeles, CA', depot: 'Service Center',
      lastPingLabel: '2 hours ago', lastPingDate: 'Feb 9, 12:15',
      health: 'Fair', healthDot: 'bg-amber-400'
    },
    {
      id: 'CO-5629', plate: 'CO-5629', model: 'Kenworth T680', category: 'Semi-Truck',
      image: 'https://plus.unsplash.com/premium_photo-1661909986326-70e6dc430ff2?w=100&h=80&fit=crop&q=80',
      status: 'Available', statusTone: 'bg-emerald-100/60 text-emerald-600',
      driver: 'David Thompson', driverAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop', driverStatus: 'Available',
      location: 'Denver, CO', depot: 'Denver Distribution Center',
      lastPingLabel: '8 minutes ago', lastPingDate: 'Feb 9, 14:26',
      health: 'Good', healthDot: 'bg-emerald-400'
    },
    {
      id: 'TRL-8901', plate: 'TRL-8901', model: '53ft Dry Van', category: 'Trailer',
      image: 'https://images.unsplash.com/photo-1591768793355-74d04bb6615f?w=100&h=80&fit=crop&q=80',
      status: 'In Use', statusTone: 'bg-amber-100/60 text-amber-600',
      driver: 'Maria Santos', driverAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop', driverStatus: 'On Route',
      location: 'Atlanta, GA', depot: 'En route to Miami',
      lastPingLabel: '1 minute ago', lastPingDate: 'Feb 9, 14:33',
      health: 'Good', healthDot: 'bg-emerald-400'
    },
    {
      id: 'NY-2847', plate: 'NY-2847', model: 'Mack Anthem', category: 'Semi-Truck',
      image: 'https://images.unsplash.com/photo-1635345472714-c8c122f48d94?w=100&h=80&fit=crop&q=80',
      status: 'Critical', statusTone: 'bg-rose-100/60 text-rose-600',
      driver: 'James Wilson', driverAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop', driverStatus: 'Emergency Stop',
      location: 'Albany, NY', depot: 'Roadside assistance needed',
      lastPingLabel: '45 minutes ago', lastPingDate: 'Feb 9, 13:49',
      health: 'Poor', healthDot: 'bg-rose-500'
    },
    {
      id: 'GA-9273', plate: 'GA-9273', model: 'International LT', category: 'Semi-Truck',
      image: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=100&h=80&fit=crop&q=80',
      status: 'In Use', statusTone: 'bg-amber-100/60 text-amber-600',
      driver: 'Robert Garcia', driverAvatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=100&h=100&fit=crop', driverStatus: 'On Route',
      location: 'Savannah, GA', depot: 'En route to Charlotte',
      lastPingLabel: '3 minutes ago', lastPingDate: 'Feb 9, 14:31',
      health: 'Good', healthDot: 'bg-emerald-400'
    },
    {
      id: 'OH-4519', plate: 'OH-4519', model: 'Western Star 5700', category: 'Semi-Truck',
      image: 'https://images.unsplash.com/photo-1586191552066-d52cd3ae57bf?w=100&h=80&fit=crop&q=80',
      status: 'Available', statusTone: 'bg-emerald-100/60 text-emerald-600',
      driver: 'Lisa Anderson', driverAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop', driverStatus: 'Available',
      location: 'Columbus, OH', depot: 'Ohio Distribution Hub',
      lastPingLabel: '10 minutes ago', lastPingDate: 'Feb 9, 14:24',
      health: 'Good', healthDot: 'bg-emerald-400'
    },
    {
      id: 'PA-6182', plate: 'PA-6182', model: 'Freightliner M2', category: 'Box Truck',
      image: 'https://images.unsplash.com/photo-1610416390145-c454e954a1be?w=100&h=80&fit=crop&q=80',
      status: 'In Use', statusTone: 'bg-amber-100/60 text-amber-600',
      driver: 'Eric Matthews', driverAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop', driverStatus: 'Delivering',
      location: 'Philadelphia, PA', depot: 'Last-mile delivery zone',
      lastPingLabel: '1 minute ago', lastPingDate: 'Feb 9, 14:33',
      health: 'Good', healthDot: 'bg-emerald-400'
    },
    {
      id: 'TRL-5540', plate: 'TRL-5540', model: '48ft Flatbed', category: 'Trailer',
      image: 'https://images.unsplash.com/photo-1591768793355-74d04bb6615f?w=100&h=80&fit=crop&q=80',
      status: 'Available', statusTone: 'bg-emerald-100/60 text-emerald-600',
      driver: 'Unassigned', driverAvatar: '', driverStatus: 'Yard parked',
      location: 'Memphis, TN', depot: 'Southwest Yard',
      lastPingLabel: '6 hours ago', lastPingDate: 'Feb 9, 08:34',
      health: 'Good', healthDot: 'bg-emerald-400'
    },
    {
      id: 'WA-3310', plate: 'WA-3310', model: 'Kenworth W990', category: 'Semi-Truck',
      image: 'https://plus.unsplash.com/premium_photo-1661909986326-70e6dc430ff2?w=100&h=80&fit=crop&q=80',
      status: 'In Use', statusTone: 'bg-amber-100/60 text-amber-600',
      driver: 'Amanda Taylor', driverAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop', driverStatus: 'On Route',
      location: 'Seattle, WA', depot: 'En route to Portland',
      lastPingLabel: '7 minutes ago', lastPingDate: 'Feb 9, 14:27',
      health: 'Good', healthDot: 'bg-emerald-400'
    },
    {
      id: 'MI-7025', plate: 'MI-7025', model: 'Peterbilt 389', category: 'Semi-Truck',
      image: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=100&h=80&fit=crop&q=80',
      status: 'Maintenance', statusTone: 'bg-rose-100/60 text-rose-600',
      driver: 'Unassigned', driverAvatar: '', driverStatus: 'Engine overhaul',
      location: 'Detroit, MI', depot: 'Authorized Service Center',
      lastPingLabel: '3 days ago', lastPingDate: 'Feb 6, 09:10',
      health: 'Poor', healthDot: 'bg-rose-500'
    },
    {
      id: 'AZ-8844', plate: 'AZ-8844', model: 'Volvo VNR', category: 'Semi-Truck',
      image: 'https://images.unsplash.com/photo-1586191552066-d52cd3ae57bf?w=100&h=80&fit=crop&q=80',
      status: 'Available', statusTone: 'bg-emerald-100/60 text-emerald-600',
      driver: 'Nathan Hill', driverAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop', driverStatus: 'Available',
      location: 'Phoenix, AZ', depot: 'Southwest Hub Terminal',
      lastPingLabel: '15 minutes ago', lastPingDate: 'Feb 9, 14:19',
      health: 'Good', healthDot: 'bg-emerald-400'
    },
    {
      id: 'NC-1196', plate: 'NC-1196', model: 'Hino L7', category: 'Box Truck',
      image: 'https://images.unsplash.com/photo-1610416390145-c454e954a1be?w=100&h=80&fit=crop&q=80',
      status: 'In Use', statusTone: 'bg-amber-100/60 text-amber-600',
      driver: 'Rachel Moore', driverAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop', driverStatus: 'Delivering',
      location: 'Raleigh, NC', depot: 'Triangle Distribution',
      lastPingLabel: '4 minutes ago', lastPingDate: 'Feb 9, 14:30',
      health: 'Fair', healthDot: 'bg-amber-400'
    },
    {
      id: 'MN-6630', plate: 'MN-6630', model: 'Navistar HV', category: 'Semi-Truck',
      image: 'https://images.unsplash.com/photo-1635345472714-c8c122f48d94?w=100&h=80&fit=crop&q=80',
      status: 'Available', statusTone: 'bg-emerald-100/60 text-emerald-600',
      driver: 'Brian Scott', driverAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop', driverStatus: 'Available',
      location: 'Minneapolis, MN', depot: 'North Central Yard',
      lastPingLabel: '22 minutes ago', lastPingDate: 'Feb 9, 14:12',
      health: 'Good', healthDot: 'bg-emerald-400'
    },
  ],
  driverSummary: [
    { id: 'total-drivers', label: 'Total Active Drivers', value: '127', icon: 'UserRound', iconTone: 'bg-blue-500 text-white', bgTone: 'bg-blue-50 border-blue-100', textTone: 'text-blue-700' },
    { id: 'available-now', label: 'Available Now', value: '84', icon: 'CheckCircle2', iconTone: 'bg-emerald-500 text-white', bgTone: 'bg-emerald-50 border-emerald-100', textTone: 'text-emerald-700' },
    { id: 'hos-risk', label: 'HOS Risk Alerts', value: '12', icon: 'Bell', iconTone: 'bg-rose-500 text-white', bgTone: 'bg-rose-50 border-rose-100', textTone: 'text-rose-700' },
    { id: 'avg-rating', label: 'Average Rating', value: '4.6', icon: 'BarChart3', iconTone: 'bg-amber-500 text-white', bgTone: 'bg-amber-50 border-amber-100', textTone: 'text-amber-700' },
  ],
  drivers: [
    {
      id: 'DRV-001',
      name: 'Michael Rodriguez',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
      licenseType: 'CDL Class A',
      experience: '8 years experience',
      status: 'Available',
      statusTone: 'bg-emerald-100 text-emerald-700',
      hosRisk: 'Low',
      hosRiskTone: 'bg-emerald-400',
      rating: 4.9,
      lastTrip: { route: 'Chicago \u2192 Atlanta', status: 'Completed Feb 8, 2024' },
      currentLocation: { city: 'Chicago, IL', terminal: 'Chicago Hub Terminal' },
      contact: { phone: '(555) 012-3456', email: 'm.rodriguez@fleetflow.com' }
    },
    {
      id: 'DRV-002',
      name: 'Jennifer Chen',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
      licenseType: 'CDL Class A',
      experience: '5 years experience',
      status: 'On Trip',
      statusTone: 'bg-amber-100 text-amber-700',
      hosRisk: 'Medium',
      hosRiskTone: 'bg-amber-500',
      rating: 4.7,
      lastTrip: { route: 'Dallas \u2192 Phoenix', status: 'In progress \u2022 ETA Feb 10' },
      currentLocation: { city: 'Dallas, TX', terminal: 'En route to Phoenix' },
      contact: { phone: '(555) 012-7890', email: 'j.chen@fleetflow.com' }
    },
    {
      id: 'DRV-003',
      name: 'David Thompson',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
      licenseType: 'CDL Class A',
      experience: '12 years experience',
      status: 'Off Duty',
      statusTone: 'bg-slate-100 text-slate-700',
      hosRisk: 'High',
      hosRiskTone: 'bg-rose-400',
      rating: 4.8,
      lastTrip: { route: 'Denver \u2192 Salt Lake City', status: 'Completed Feb 7, 2024' },
      currentLocation: { city: 'Denver, CO', terminal: 'Rest period \u2022 34hr reset' },
      contact: { phone: '(555) 012-1122', email: 'd.thompson@fleetflow.com' }
    },
    {
      id: 'DRV-004',
      name: 'Maria Santos',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
      licenseType: 'CDL Class A',
      experience: '6 years experience',
      status: 'On Trip',
      statusTone: 'bg-amber-100 text-amber-700',
      hosRisk: 'Low',
      hosRiskTone: 'bg-emerald-400',
      rating: 4.6,
      lastTrip: { route: 'Atlanta \u2192 Miami', status: 'In progress \u2022 ETA Feb 9' },
      currentLocation: { city: 'Atlanta, GA', terminal: 'En route to Miami' },
      contact: { phone: '(555) 012-3344', email: 'm.santos@fleetflow.com' }
    },
    {
      id: 'DRV-005',
      name: 'James Wilson',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
      licenseType: 'CDL Class A',
      experience: '9 years experience',
      status: 'Available',
      statusTone: 'bg-emerald-100 text-emerald-700',
      hosRisk: 'Low',
      hosRiskTone: 'bg-emerald-400',
      rating: 4.9,
      lastTrip: { route: 'New York \u2192 Boston', status: 'Completed Feb 8, 2024' },
      currentLocation: { city: 'Albany, NY', terminal: 'Rest area \u2022 I-90' },
      contact: { phone: '(555) 012-5566', email: 'j.wilson@fleetflow.com' }
    },
    {
      id: 'DRV-006',
      name: 'Rachel Moore',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop',
      licenseType: 'CDL Class A',
      experience: '4 years experience',
      status: 'Available',
      statusTone: 'bg-emerald-100 text-emerald-700',
      hosRisk: 'Medium',
      hosRiskTone: 'bg-amber-500',
      rating: 4.7,
      lastTrip: { route: 'St. Louis \u2192 Indianapolis', status: 'Completed Feb 8, 2024' },
      currentLocation: { city: 'Indianapolis, IN', terminal: 'Logistics Hub' },
      contact: { phone: '(555) 012-7788', email: 'r.moore@fleetflow.com' }
    },
    {
      id: 'DRV-007',
      name: 'James Martinez',
      avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=100&h=100&fit=crop',
      licenseType: 'CDL Class A',
      experience: '7 years experience',
      status: 'On Trip',
      statusTone: 'bg-amber-100 text-amber-700',
      hosRisk: 'Low',
      hosRiskTone: 'bg-emerald-400',
      rating: 4.8,
      lastTrip: { route: 'Portland \u2192 San Francisco', status: 'In progress' },
      currentLocation: { city: 'Medford, OR', terminal: 'Fueling Stop' },
      contact: { phone: '(555) 012-9900', email: 'j.martinez@fleetflow.com' }
    },
    {
      id: 'DRV-008',
      name: 'Lisa Anderson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
      licenseType: 'CDL Class A',
      experience: '10 years experience',
      status: 'Off Duty',
      statusTone: 'bg-slate-100 text-slate-700',
      hosRisk: 'Low',
      hosRiskTone: 'bg-emerald-400',
      rating: 5.0,
      lastTrip: { route: 'Denver \u2192 Kansas City', status: 'Completed Feb 7' },
      currentLocation: { city: 'Kansas City, MO', terminal: 'Home' },
      contact: { phone: '(555) 012-1234', email: 'l.anderson@fleetflow.com' }
    },
    {
      id: 'DRV-009',
      name: 'Robert Wilson',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop',
      licenseType: 'CDL Class A',
      experience: '11 years experience',
      status: 'Available',
      statusTone: 'bg-emerald-100 text-emerald-700',
      hosRisk: 'Medium',
      hosRiskTone: 'bg-amber-500',
      rating: 4.5,
      lastTrip: { route: 'Houston \u2192 New Orleans', status: 'Completed Feb 9' },
      currentLocation: { city: 'New Orleans, LA', terminal: 'Hub' },
      contact: { phone: '(555) 012-5678', email: 'r.wilson@fleetflow.com' }
    },
    {
      id: 'DRV-010',
      name: 'Amanda Taylor',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop',
      licenseType: 'CDL Class A',
      experience: '3 years experience',
      status: 'On Trip',
      statusTone: 'bg-amber-100 text-amber-700',
      hosRisk: 'Low',
      hosRiskTone: 'bg-emerald-400',
      rating: 4.6,
      lastTrip: { route: 'Nashville \u2192 Memphis', status: 'In progress' },
      currentLocation: { city: 'Jackson, TN', terminal: 'En route' },
      contact: { phone: '(555) 012-9012', email: 'a.taylor@fleetflow.com' }
    }
  ],
  routeSummary: [
    { id: 'active-routes', label: 'Active Routes', value: '23', icon: 'Route', bgTone: 'bg-blue-50', textTone: 'text-blue-600', iconTone: 'bg-blue-100 text-blue-600' },
    { id: 'on-time-perf', label: 'On-Time Performance', value: '94.2%', icon: 'Clock3', bgTone: 'bg-emerald-50', textTone: 'text-emerald-600', iconTone: 'bg-emerald-100 text-emerald-600' },
    { id: 'critical-delays', label: 'Critical Delays', value: '3', icon: 'AlertTriangle', bgTone: 'bg-rose-50', textTone: 'text-rose-600', iconTone: 'bg-rose-100 text-rose-600' },
    { id: 'fleet-status', label: 'Fleet Status', value: '18/20', icon: 'Truck', bgTone: 'bg-violet-50', textTone: 'text-violet-600', iconTone: 'bg-violet-100 text-violet-600' },
  ],
  routesTracking: [
    {
      id: 'TRK-001',
      driver: 'Michael Rodriguez',
      status: 'On-time',
      origin: 'Washington, DC',
      currentLocation: { lat: 38.9072, lng: -77.0369, city: 'Washington, DC' },
      destination: { lat: 34.0522, lng: -118.2437, city: 'Los Angeles, CA' },
      progress: 65,
      distanceRemaining: '840 miles',
      etaHours: '14h 30m',
      delayTime: '0 min',
      eta: 'Feb 12, 10:30 PM',
      path: [{ lat: 38.9072, lng: -77.0369 }, { lat: 39.9612, lng: -82.9988 }, { lat: 38.6270, lng: -90.1994 }, { lat: 35.4676, lng: -97.5164 }, { lat: 35.0844, lng: -106.6504 }],
      stops: [
        { id: 'S1', type: 'Pickup', location: 'Washington, DC', status: 'Completed' },
        { id: 'S2', type: 'Fuel', location: 'Columbus, OH', status: 'In progress' },
        { id: 'S3', type: 'Delivery', location: 'Los Angeles, CA', status: 'Pending' }
      ]
    },
    {
      id: 'TRK-002',
      driver: 'Jennifer Chen',
      status: 'Delayed',
      origin: 'New York, NY',
      currentLocation: { lat: 40.7128, lng: -74.0060, city: 'New York, NY' },
      destination: { lat: 41.8781, lng: -87.6298, city: 'Chicago, IL' },
      progress: 42,
      distanceRemaining: '520 miles',
      etaHours: '8h 15m',
      delayTime: '45 min',
      eta: 'Feb 11, 04:15 AM',
      path: [{ lat: 40.7128, lng: -74.0060 }, { lat: 40.4406, lng: -79.9959 }, { lat: 41.4993, lng: -81.6944 }, { lat: 41.8781, lng: -87.6298 }],
      stops: [
        { id: 'S1', type: 'Pickup', location: 'New York, NY', status: 'Completed' },
        { id: 'S2', type: 'Delivery', location: 'Chicago, IL', status: 'In progress' }
      ]
    },
    {
      id: 'TRK-003',
      driver: 'David Thompson',
      status: 'Critical Delay',
      origin: 'Houston, TX',
      currentLocation: { lat: 29.7604, lng: -95.3698, city: 'Houston, TX' },
      destination: { lat: 30.2672, lng: -97.7431, city: 'Austin, TX' },
      progress: 88,
      distanceRemaining: '45 miles',
      etaHours: '1h 10m',
      delayTime: '120 min',
      eta: 'Feb 10, 11:45 PM',
      path: [{ lat: 29.7604, lng: -95.3698 }, { lat: 29.9722, lng: -95.6722 }, { lat: 30.2672, lng: -97.7431 }],
      stops: [
        { id: 'S1', type: 'Pickup', location: 'Houston, TX', status: 'Completed' },
        { id: 'S2', type: 'Delivery', location: 'Austin, TX', status: 'In progress' }
      ]
    },
    {
      id: 'TRK-004',
      driver: 'Maria Santos',
      status: 'On-time',
      origin: 'Miami, FL',
      currentLocation: { lat: 25.7617, lng: -80.1918, city: 'Miami, FL' },
      destination: { lat: 33.7490, lng: -84.3880, city: 'Atlanta, GA' },
      progress: 30,
      distanceRemaining: '460 miles',
      etaHours: '7h 45m',
      delayTime: '0 min',
      eta: 'Feb 12, 08:00 AM',
      path: [{ lat: 25.7617, lng: -80.1918 }, { lat: 28.5383, lng: -81.3792 }, { lat: 30.3322, lng: -81.6557 }, { lat: 33.7490, lng: -84.3880 }],
      stops: [
        { id: 'S1', type: 'Pickup', location: 'Miami, FL', status: 'Completed' },
        { id: 'S2', type: 'Delivery', location: 'Atlanta, GA', status: 'Pending' }
      ]
    },
    {
      id: 'TRK-005',
      driver: 'James Wilson',
      status: 'Active',
      origin: 'Seattle, WA',
      currentLocation: { lat: 47.6062, lng: -122.3321, city: 'Seattle, WA' },
      destination: { lat: 45.5152, lng: -122.6784, city: 'Portland, OR' },
      progress: 15,
      distanceRemaining: '150 miles',
      etaHours: '2h 50m',
      delayTime: '0 min',
      eta: 'Feb 11, 06:30 PM',
      path: [{ lat: 47.6062, lng: -122.3321 }, { lat: 47.2529, lng: -122.4443 }, { lat: 45.5152, lng: -122.6784 }],
      stops: [
        { id: 'S1', type: 'Pickup', location: 'Seattle, WA', status: 'Completed' },
        { id: 'S2', type: 'Delivery', location: 'Portland, OR', status: 'In progress' }
      ]
    }
  ],
  billingStats: [
    { id: 'total-outstanding', label: 'Total Outstanding', value: '$245,890', note: '12 invoices due soon', icon: 'Wallet', iconTone: 'bg-emerald-100 text-emerald-600', noteTone: 'text-emerald-500' },
    { id: 'overdue-amount', label: 'Overdue Amount', value: '$42,500', note: '3 critical overdue', icon: 'AlertTriangle', iconTone: 'bg-rose-100 text-rose-600', noteTone: 'text-rose-500' },
    { id: 'processed-this-month', label: 'Processed (MTD)', value: '$890,200', note: '+15% vs last month', icon: 'FileCheck2', iconTone: 'bg-blue-100 text-blue-600', noteTone: 'text-emerald-500' },
  ],
  invoiceTabs: ['All Invoices', 'Pending', 'Paid', 'Overdue'],
  invoiceList: [
    {
      id: 'INV-2024-8831',
      customerName: 'Walmart Distribution',
      customerAddress: 'Chicago, IL',
      issueDate: '01 Feb, 2024',
      dueDate: '15 Feb, 2024',
      amount: '$12,450.00',
      status: 'Pending',
      tone: 'bg-[#eff6ff] text-[#3b82f6]',
      statusDots: ['bg-blue-300', 'bg-blue-400', 'bg-slate-200'],
      actionLabel: 'Send Reminder',
      actionTone: 'bg-blue-50 text-blue-600 hover:bg-blue-100',
      secondAction: 'Download',
      secondTone: 'bg-slate-50 text-slate-600 hover:bg-slate-100',
    },
    {
      id: 'INV-2024-8832',
      customerName: 'Target Corporation',
      customerAddress: 'Dallas, TX',
      issueDate: '28 Jan, 2024',
      dueDate: '10 Feb, 2024',
      amount: '$8,920.00',
      status: 'Overdue',
      tone: 'bg-[#fef2f2] text-[#ef4444]',
      statusDots: ['bg-red-400', 'bg-red-500', 'bg-red-600'],
      actionLabel: 'Escalate',
      actionTone: 'bg-rose-50 text-rose-600 hover:bg-rose-100',
      secondAction: 'Download',
      secondTone: 'bg-slate-50 text-slate-600 hover:bg-slate-100',
    },
    {
      id: 'INV-2024-8833',
      customerName: 'Amazon Logistics',
      customerAddress: 'Los Angeles, CA',
      issueDate: '15 Jan, 2024',
      dueDate: '30 Jan, 2024',
      amount: '$24,100.00',
      status: 'Paid',
      tone: 'bg-[#ecfdf5] text-[#10b981]',
      statusDots: ['bg-emerald-300', 'bg-emerald-400', 'bg-emerald-500'],
      actionLabel: 'View Receipt',
      actionTone: 'bg-emerald-50 text-emerald-600 hover:bg-emerald-100',
      secondAction: 'Download',
      secondTone: 'bg-slate-50 text-slate-600 hover:bg-slate-100',
    },
    {
      id: 'INV-2024-8834',
      customerName: 'FedEx Ground',
      customerAddress: 'Miami, FL',
      issueDate: '05 Feb, 2024',
      dueDate: '20 Feb, 2024',
      amount: '$3,400.00',
      status: 'Pending',
      tone: 'bg-[#eff6ff] text-[#3b82f6]',
      statusDots: ['bg-blue-300', 'bg-blue-400', 'bg-slate-200'],
      actionLabel: 'Send Reminder',
      actionTone: 'bg-blue-50 text-blue-600 hover:bg-blue-100',
      secondAction: 'Download',
      secondTone: 'bg-slate-50 text-slate-600 hover:bg-slate-100',
    },
    {
      id: 'INV-2024-8835',
      customerName: 'Home Depot Supply',
      customerAddress: 'Houston, TX',
      issueDate: '02 Feb, 2024',
      dueDate: '16 Feb, 2024',
      amount: '$6,850.00',
      status: 'Pending',
      tone: 'bg-[#eff6ff] text-[#3b82f6]',
      statusDots: ['bg-blue-300', 'bg-blue-400', 'bg-slate-200'],
      actionLabel: 'Send Reminder',
      actionTone: 'bg-blue-50 text-blue-600 hover:bg-blue-100',
      secondAction: 'Download',
      secondTone: 'bg-slate-50 text-slate-600 hover:bg-slate-100',
    },
    {
      id: 'INV-2024-8836',
      customerName: 'Costco Wholesale',
      customerAddress: 'Denver, CO',
      issueDate: '20 Jan, 2024',
      dueDate: '04 Feb, 2024',
      amount: '$15,200.00',
      status: 'Overdue',
      tone: 'bg-[#fef2f2] text-[#ef4444]',
      statusDots: ['bg-red-400', 'bg-red-500', 'bg-red-600'],
      actionLabel: 'Escalate',
      actionTone: 'bg-rose-50 text-rose-600 hover:bg-rose-100',
      secondAction: 'Download',
      secondTone: 'bg-slate-50 text-slate-600 hover:bg-slate-100',
    },
    {
      id: 'INV-2024-8837',
      customerName: 'Safeway Distribution',
      customerAddress: 'Portland, OR',
      issueDate: '10 Jan, 2024',
      dueDate: '25 Jan, 2024',
      amount: '$4,150.00',
      status: 'Paid',
      tone: 'bg-[#ecfdf5] text-[#10b981]',
      statusDots: ['bg-emerald-300', 'bg-emerald-400', 'bg-emerald-500'],
      actionLabel: 'View Receipt',
      actionTone: 'bg-emerald-50 text-emerald-600 hover:bg-emerald-100',
      secondAction: 'Download',
      secondTone: 'bg-slate-50 text-slate-600 hover:bg-slate-100',
    },
    {
      id: 'INV-2024-8838',
      customerName: 'Whole Foods Market',
      customerAddress: 'Sacramento, CA',
      issueDate: '18 Jan, 2024',
      dueDate: '02 Feb, 2024',
      amount: '$9,300.00',
      status: 'Paid',
      tone: 'bg-[#ecfdf5] text-[#10b981]',
      statusDots: ['bg-emerald-300', 'bg-emerald-400', 'bg-emerald-500'],
      actionLabel: 'View Receipt',
      actionTone: 'bg-emerald-50 text-emerald-600 hover:bg-emerald-100',
      secondAction: 'Download',
      secondTone: 'bg-slate-50 text-slate-600 hover:bg-slate-100',
    },
  ],
}
